# Bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

eval "$(rbenv init -)"

set -o vi # vi mode

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWCOLORHINTS=true
export PS1='\[`tput setaf 325`\]$PWD\[`tput sgr0`\]$(__git_ps1 " (%s)") $ '
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Golang
export GOPATH=~/go
export GOBIN=$GOPATH/bin
export PATH=$GOPATH:$GOBIN:$PATH

# Aliases
alias g="git"
alias push="git push && hub pull-request"
alias pfush="git push --force && hub pull-request"
alias l="ls -la"
alias c="clear"
alias dotfiles="cd ~/dotfiles && nvim"
alias n="nvim"
alias nn="nvim -S" # start nvim with last session
alias rc="bundler exec rails console"
alias be="bundle exec"
alias remigrate="bundler exec rake db:drop db:create db:migrate"
alias check="be rubocop -a && be rspec"

# Functions
mkcdir ()
{
    mkdir -p -- "$1" &&
    cd -P -- "$1"
}

tag ()
{
    ctags -R .
}

tag-ruby ()
{
    ctags -R . `bundle show --paths`
}

weather ()
{
    curl wttr.in
}

psearch ()
{
    ps -ax | grep -i "$1"
}

gfind ()
{
    grep -RF "$1" "$2"
}

backup ()
{
    tar -czvf "$1.tar.gz" "$1"
}

prettify_json ()
{
    if [[ -z $1 ]]; then
        ruby -e "require 'json'; puts JSON.pretty_generate(JSON.parse(STDIN.read))"
    else
        ruby -e "require 'json'; IO.write('$1.pretty', JSON.pretty_generate(JSON.parse(IO.read('$1'))))"
    fi
}

share ()
{
    gdrive upload $1 --share
}

recognize ()
{
    bundler exec rails r "puts; puts; puts Rails.application.routes.recognize_path('$1')"
}
